# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='model',
            field=models.CharField(choices=[('knee', 'knee'), ('gait', 'gait')], default='knee', max_length=128),
        ),
    ]
